"""empty message

Revision ID: 1a31dd6e0dfe
Revises: 44f3cc99fee4
Create Date: 2024-07-09 20:08:44.496709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a31dd6e0dfe'
down_revision = '44f3cc99fee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('channel_id',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.DECIMAL(precision=2, scale=1),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('channel_id',
               existing_type=sa.DECIMAL(precision=2, scale=1),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)

    # ### end Alembic commands ###
