"""add time in  WorkingData

Revision ID: 28852bef8034
Revises: 86ebad2d781e
Create Date: 2024-07-02 21:08:06.513849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28852bef8034'
down_revision = '86ebad2d781e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_data', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
