"""remove channel foreign key

Revision ID: 292607d0f4df
Revises: 2c6afcb1a3df
Create Date: 2024-08-12 17:31:06.986474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '292607d0f4df'
down_revision = '2c6afcb1a3df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('channel_id',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('channel_id',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=False)

    # ### end Alembic commands ###
