"""empty message

Revision ID: 44f3cc99fee4
Revises: 28852bef8034
Create Date: 2024-07-09 19:29:48.015020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44f3cc99fee4'
down_revision = '28852bef8034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pwd_hash',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pwd_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
