"""remove channel foreign key

Revision ID: 60fbd7866fb3
Revises: 7fd7366f667b
Create Date: 2024-08-12 18:02:20.707086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60fbd7866fb3'
down_revision = '7fd7366f667b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=False)

    # ### end Alembic commands ###
