"""add lower limit in sensors

Revision ID: 6ff1e23c55de
Revises: f6854dd66e85
Create Date: 2024-08-12 23:03:04.516241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff1e23c55de'
down_revision = 'f6854dd66e85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lowerlimit_mean', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lowerlimit_rms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lowerlimit_std', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('lowerlimit_std')
        batch_op.drop_column('lowerlimit_rms')
        batch_op.drop_column('lowerlimit_mean')

    # ### end Alembic commands ###
