"""add foreign key on channel

Revision ID: 7fd7366f667b
Revises: 292607d0f4df
Create Date: 2024-08-12 17:48:24.413366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fd7366f667b'
down_revision = '292607d0f4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=False)
        batch_op.create_foreign_key(None, 'sensors', ['channel'], ['channel_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('channel',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=True)

    # ### end Alembic commands ###
