"""Initial migration

Revision ID: 9bc99c8680f3
Revises: 
Create Date: 2024-07-02 12:52:38.697729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bc99c8680f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('mean',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('rms',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('std',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('fft_1',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('fft_2',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('fft_3',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('fft_4',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('fft_5',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('fft_6',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('fft_7',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('fft_8',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    with op.batch_alter_table('machine_list', schema=None) as batch_op:
        batch_op.alter_column('machine',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('machine_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('work_piece',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('cutting_tool',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('machine_type',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)

    with op.batch_alter_table('sensor_list', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('sensor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('machine',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('channel_id',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('location_x',
               existing_type=mysql.DECIMAL(precision=5, scale=1),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('location_y',
               existing_type=mysql.DECIMAL(precision=5, scale=1),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('location_z',
               existing_type=mysql.DECIMAL(precision=5, scale=1),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('safelimit_mean',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('safelimit_rms',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('safelimit_std',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.create_foreign_key(None, 'sensor_list', ['sensor_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)
        batch_op.alter_column('pwd_hash',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('pwd_hash',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('safelimit_std',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('safelimit_rms',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('safelimit_mean',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('location_z',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=1),
               nullable=False)
        batch_op.alter_column('location_y',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=1),
               nullable=False)
        batch_op.alter_column('location_x',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=1),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('channel_id',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=2, scale=1),
               nullable=False)
        batch_op.alter_column('machine',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('sensor_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('sensor_list', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.alter_column('machine_type',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('cutting_tool',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('work_piece',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('machine_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('machine_list', schema=None) as batch_op:
        batch_op.alter_column('machine',
               existing_type=sa.String(length=30),
               type_=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('fft_8',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('fft_7',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('fft_6',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('fft_5',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('fft_4',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('fft_3',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('fft_2',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('fft_1',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('std',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('rms',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('mean',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=2),
               nullable=False)
        batch_op.alter_column('channel',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=2, scale=1),
               nullable=False)

    # ### end Alembic commands ###
