"""add foreign key

Revision ID: c803863b97c6
Revises: 7201e9181da9
Create Date: 2024-08-12 17:21:38.236145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c803863b97c6'
down_revision = '7201e9181da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.alter_column('channel_id',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=False)
        batch_op.create_foreign_key(None, 'channel', ['channel_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('channel_id',
               existing_type=mysql.DECIMAL(precision=2, scale=1),
               nullable=True)

    # ### end Alembic commands ###
